// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WelcomeAppWithMVVM_EF_Core.Models;

namespace WelcomeAppWithMVVM_EF_Core.Migrations
{
    [DbContext(typeof(WelcomeAppDbContext))]
    partial class WelcomeAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WelcomeAppWithMVVM_EF_Core.Models.Greeting", b =>
                {
                    b.Property<int>("GreetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GreetingId");

                    b.HasIndex("JobId");

                    b.ToTable("Greetings");
                });

            modelBuilder.Entity("WelcomeAppWithMVVM_EF_Core.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            Title = "Étudiant"
                        },
                        new
                        {
                            JobId = 2,
                            Title = "Ingénieur"
                        },
                        new
                        {
                            JobId = 3,
                            Title = "Professeur"
                        },
                        new
                        {
                            JobId = 4,
                            Title = "Directeur"
                        });
                });

            modelBuilder.Entity("WelcomeAppWithMVVM_EF_Core.Models.Greeting", b =>
                {
                    b.HasOne("WelcomeAppWithMVVM_EF_Core.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
